# WIP. Every image directory needs a new trigger that points to this Cloudbuild and sets a few overrides

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull ${_IMAGE_NAME}:buildcache || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  dir: "${_BUILD_DIR}"
  args: [
    'build',
    '-t', '${_IMAGE_NAME}:buildcache',
    '-t', '${_IMAGE_NAME}:$COMMIT_SHA',
    '--cache-from', '${_IMAGE_NAME}:buildcache',
    '.'
  ]
images: [
    '${_IMAGE_NAME}:buildcache',
    '${_IMAGE_NAME}:$COMMIT_SHA',
  ]
timeout: 3600s
