### Note:
# This deployment is currently unused. It is supposed to be a JMX bridge that exposes Kafka metrics via Prometheus,
# but it doesn't export such values as consumer group lag, and only adds unnecessary complexity to the setup. So disabled for now.

{% set labels = {
  "service": "zookafka",
  "component": "jmx-exporter",
} %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookafka-jmx-exporter
  labels: {{ labels }}
spec:
  replicas: 0
  selector:
    matchLabels: {{ labels }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ labels }}
      annotations:
        configVersion: "{{ md5template("configmap-metrics-exporter.yaml") }}"
    spec:
      containers:
      # JMX Exporter
      - image: bitnami/jmx-exporter:0.16.1
        name: jmx-exporter
        command:
        - "java"
        - "-Djava.util.logging.config.file=/etc/logging.properties"
        - "-jar"
        - "jmx_prometheus_httpserver.jar"
        args:
        - "8081"
        - /etc/kafka.yaml
        volumeMounts:
        - name: jmx-exporter-config
          mountPath: /etc/kafka.yaml
          subPath: kafka.yaml
        - name: jmx-exporter-config
          mountPath: /etc/logging.properties
          subPath: logging.properties
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 200Mi
      volumes:
      - name: jmx-exporter-config
        configMap:
          name: jmx-exporter-config
      dnsConfig:
        options:
          - name: ndots
            value: "1"
