# TODO: use *-retain storage classes when recreating these PVCs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
