
environments:
  main:
    replicas: 1
    autoscaler:
      enabled: false


### Envoy configuration ###

envoy_config:
  static_resources:
    clusters:
    - name: "relay-envoy"
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: "relay-envoy"
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: "127.0.0.1"
                  port_value: "3000"
      common_http_protocol_options:
        # This is the idle timeout for upstream connections.
        # Upstream implementation (relay's actix) has default idle timeout of 5 seconds, so we need to make it lower here,
        # to avoid races when closing idle connections.
        idle_timeout: 4s
      circuit_breakers:
        thresholds:
          - priority: "DEFAULT"
            max_retries: 10000
            max_connections: 50000
            max_requests: 50000
            max_pending_requests: 50000
            track_remaining: True
    - name: xds_cluster
      type: LOGICAL_DNS
      connect_timeout: 0.5s
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: xds.service.sentry.internal
                  port_value: 80

    listeners:
    - address:
        socket_address:
          address: "0.0.0.0"
          port_value: "3010"
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            codec_type: auto
            stat_prefix: envoy_local
            route_config:
              name: local_route
              virtual_hosts:
              - name: service
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: "relay-envoy"
                    retry_policy:
                      retry_on: connect-failure
                      num_retries: 3
            access_log:
            - name: envoy.access_loggers.file
              filter:
                status_code_filter:
                  comparison:
                    op: GE
                    value:
                      default_value: 500
                      runtime_key: access_log_50X_errors
              config:
                path: "/dev/stdout"
                json_format:
                  method: "%REQ(:METHOD)%"
                  path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                  upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                  request_id: "%REQ(X-REQUEST-ID)%"
                  protocol: "%PROTOCOL%"
                  duration: "%DURATION%"
                  response_duration: "%RESPONSE_DURATION%"
                  response_code: "%RESPONSE_CODE%"
                  response_code_details: "%RESPONSE_CODE_DETAILS%"
                  bytes_sent: "%BYTES_SENT%"
                  bytes_received: "%BYTES_RECEIVED%"
                  response_flags: "%RESPONSE_FLAGS%"
                  upstream_host: "%UPSTREAM_HOST%"
                  downstream_remote_host: "%DOWNSTREAM_REMOTE_ADDRESS%"
                  local_reply_body: "%LOCAL_REPLY_BODY%"
            http_filters:
            # Buffer request body before routing
            - name: envoy.filters.http.buffer
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.http.buffer.v2.Buffer
                # Max request size (100 * 1024 * 1024), if request is bigger - 413 is returned
                max_request_bytes: 104857600
            - name: envoy.filters.http.router

  admin:
    access_log_path: "/dev/null"
    address:
      socket_address:
        address: "127.0.0.1"
        port_value: "9901"
  stats_sinks:
    - name: envoy.dog_statsd
      typed_config:
        "@type": type.googleapis.com/envoy.config.metrics.v2.DogStatsdSink
        prefix: envoy
        address:
          socket_address:
            address: "127.0.0.1"
            port_value: "8126"

  dynamic_resources:
    lds_config:
      api_config_source:
        api_type: REST
        cluster_names: [xds_cluster]
        refresh_delay: 60s
        request_timeout: 1s

    cds_config:
      api_config_source:
        api_type: REST
        cluster_names: [xds_cluster]
        refresh_delay: 60s
        request_timeout: 1s
