{% set labels = {
  "service": "memcached",
  "component": "server",
} %}
{% set threads = 4 %}
{% set memory_mb = 4000 %}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-sentry
  labels: {{ labels }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ labels }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ labels }}
    spec:
      containers:
      - image: memcached:1.6.7-alpine
        name: memcached-sentry
        args:
        - --listen
        - '0.0.0.0'
        - --port
        - '11211'
        - --memory-limit
        - '{{ memory_mb }}'
        - --conn-limit
        - '4096'
        - --max-item-size
        - '5m'
        - --verbose
        - --extended
        - modern,maxconns_fast
        - --threads
        - '{{ threads }}'
        ports:
        - containerPort: 11211
        resources:
          requests:
            cpu: 400m
            memory: {{ memory_mb }}Mi
          limits:
            cpu: {{ threads }}
            memory: {{ memory_mb }}Mi
