apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: relay-locust-load-test
  namespace: argo
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  arguments:
    parameters:
    - name: test_factory_branch
      value: "main"
    - name: test_duration
      value: "default"
    - name: test_users
      value: "default"
    - name: comment
      value: ""
  entrypoint: main
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: main
    dag:
      tasks:
      # Prepare
      - name: prepare-run
        templateRef:
          name: z-prepare-run
          template: prepare-run
      # Relay
      - name: relay-update-configuration
        templateRef:
          name: z-deploy-relay
          template: relay-update-configuration
        depends: prepare-run
      - name: relay-wait-for-rollout
        templateRef:
          name: z-deploy-relay
          template: relay-wait-for-rollout
        depends: relay-update-configuration
      # Locust
      - name: locust-update-configuration
        templateRef:
          name: z-deploy-locust
          template: locust-update-configuration
        depends: prepare-run
      - name: locust-wait-for-rollout
        templateRef:
          name: z-deploy-locust
          template: locust-wait-for-rollout
        depends: locust-update-configuration
      # Test!
      - name: run-test
        templateRef:
          name: z-run-test
          template: run-test
        arguments:
          parameters:
          - name: test_duration
            value: '{% raw %}{{workflow.outputs.parameters.test_duration}}{% endraw %}'
          - name: test_users
            value: '{% raw %}{{workflow.outputs.parameters.test_users}}{% endraw %}'
          - name: test_override
            value: '{% raw %}{{workflow.outputs.parameters.test_override}}{% endraw %}'
          artifacts:
          - name: run_manifest
            from: '{% raw %}{{workflow.outputs.artifacts.run_manifest}}{% endraw %}'
        depends: "relay-wait-for-rollout && locust-wait-for-rollout"
    inputs: {}
    metadata: {}
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 3600
