apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: relay-load-test
  namespace: argo
  labels:
    example: "true"
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  arguments:
    parameters:
    - name: relay_version
      value: 07786352f563dce248b23f091f6764efe38dc03c
    - name: test_duration
      value: 30s
    - name: test_users
      value: "10"
  entrypoint: main
  podGC:
    strategy: OnPodCompletion
  templates:
  - name: main
    dag:
      tasks:
      - arguments:
          parameters:
          - name: relay_version
            value: '{% raw %}{{workflow.parameters.relay_version}}{% endraw %}'
        name: update-relay-version
        template: update-relay-version
      - arguments: {}
        depends: update-relay-version
        name: wait-for-rollout
        template: wait-for-rollout
      - arguments: {}
        depends: wait-for-rollout
        name: run-test
        template: run-test
    inputs: {}
    metadata: {}
    outputs: {}
  - name: update-relay-version
    inputs:
      parameters:
      - name: relay_version
        value: '{% raw %}{{workflow.parameters.relay_version}}{% endraw %}'
    metadata: {}
    outputs: {}
    resource:
      action: patch
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: relay-main
          namespace: default
        spec:
          template:
            metadata:
              annotations:
                argoWorkflowId: "{% raw %}{{workflow.uid}}{% endraw %}"
            spec:
              containers:
              - image: us.gcr.io/sentryio/relay:{% raw %}{{inputs.parameters.relay_version}}{% endraw %}
                name: relay
  - name: wait-for-rollout
    container:
      command:
      - kubectl
      - rollout
      - status
      - deployment
      - --namespace=default
      - relay-main
      - --timeout=60s
      image: bitnami/kubectl:1.19
      name: kubectl
      resources: {}
    inputs: {}
    metadata: {}
    outputs: {}
    serviceAccountName: default
  - name: run-test
    container:
      args:
      - --duration
      - '{% raw %}{{inputs.parameters.test_duration}}{% endraw %}'
      - --users
      - '{% raw %}{{inputs.parameters.test_users}}{% endraw %}'
      - --organisation
      - f1c58f1d769114e6
      - --board
      - 08830e9216d27000
      command:
      - /load-starter
      env:
      - name: SLACK_AUTH_TOKEN
        value: xoxb-2757754192454-2766782134324-oK6ewxLGOlElIk4UE9nYTTpY
      - name: SLACK_CHANNEL_ID
        value: '#slack-notif-test'
      name: load-starter
      image: europe-west3-docker.pkg.dev/sentry-st-testing/main/load-starter:514e11da6a8e2cd137058f89434d0c4f4e6daffd
      resources: {}
    inputs:
      parameters:
      - name: test_duration
        value: '{% raw %}{{workflow.parameters.test_duration}}{% endraw %}'
      - name: test_users
        value: '{% raw %}{{workflow.parameters.test_users}}{% endraw %}'
    metadata: {}
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 3600
  workflowMetadata:
    labels:
      example: "true"
