apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: relay-load-test
  namespace: argo
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  # Disallow to run this workflow in parallel
  synchronization:
    mutex:
      name: relay-load-test
  arguments:
    parameters:
    - name: test_factory_branch
      value: "main"
    - name: test_duration
      value: "default"
    - name: test_users
      value: "default"
    - name: comment
      value: ""
  entrypoint: main
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: main
    dag:
      tasks:
      # Prepare
      - name: prepare-run
        templateRef:
          name: z-prepare-run
          template: prepare-run
        arguments:
          parameters:
          - name: test_factory_branch
            value: "{% raw %}{{workflow.parameters.test_factory_branch}}{% endraw %}"
          - name: test_duration
            value: "{% raw %}{{workflow.parameters.test_duration}}{% endraw %}"
          - name: test_users
            value: "{% raw %}{{workflow.parameters.test_users}}{% endraw %}"
      # Stop sentry components (we don't need them for this test)
      - name: sentry-stop-all
        templateRef:
          name: z-sentry
          template: sentry-stop-all
      # Relay
      - name: relay-update-configuration
        templateRef:
          name: z-relay
          template: relay-update-configuration
        depends: "prepare-run && sentry-stop-all"
      # Load tester
      - name: ingest-load-tester-update-configuration
        templateRef:
          name: z-ingest-load-tester
          template: ingest-load-tester-update-configuration
        depends: prepare-run
      # Test!
      - name: run-test
        templateRef:
          name: z-run-test
          template: run-test
        arguments:
          parameters:
          - name: test_duration
            value: '{% raw %}{{workflow.outputs.parameters.test_duration}}{% endraw %}'
          - name: test_users
            value: '{% raw %}{{workflow.outputs.parameters.test_users}}{% endraw %}'
          - name: test_override
            value: '{% raw %}{{workflow.outputs.parameters.test_override}}{% endraw %}'
          artifacts:
          - name: run_manifest
            from: '{% raw %}{{workflow.outputs.artifacts.run_manifest}}{% endraw %}'
        depends: "relay-update-configuration && ingest-load-tester-update-configuration"
      - name: run-stats
        templateRef:
          name: z-run-test
          template: run-stats-collector
        arguments:
          artifacts:
            - name: run_report
              from: '{% raw %}{{workflow.outputs.artifacts.run_report}}{% endraw %}'
        depends: run-test
    inputs: {}
    metadata: {}
    outputs: {}
  ttlStrategy:
    # 3 days
    secondsAfterCompletion: 259200
