apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-clickhouse
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: flush-clickhouse
    container:
      name: flush-clickhouse
      image: yandex/clickhouse-client:21.8.14
      command:
      - bash
      - -c
      - |
        exec 2>&1
        set -euxo pipefail

        CLICKHOUSE_HOST="{{ values.clickhouse_hostname }}"

        clickhouse-client --host "${CLICKHOUSE_HOST}" --query 'DROP DATABASE IF EXISTS default'
        clickhouse-client --host "${CLICKHOUSE_HOST}" --query 'CREATE DATABASE default'
  ttlStrategy:
    # 3 days
    secondsAfterCompletion: 259200
