apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-data-generator
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: run-ingest-metrics-generator
      inputs:
        artifacts:
          - name: ingest_metrics_generator_settings
            path: /etc/ingest-metrics-generator-settings.yaml
        parameters:
          - name: num_messages
          - name: releases
          - name: environments
      container:
        command:
          - 'python'
          - 'main.py'
          - '--settings-file'
          - '/etc/ingest-metrics-generator-settings.yaml'
          - '--num-messages'
          - '{% raw %}{{inputs.parameters.num_messages}}{% endraw %}'
          - '--releases'
          - '{% raw %}{{inputs.parameters.releases}}{% endraw %}'
          - '--environments'
          - '{% raw %}{{inputs.parameters.environments}}{% endraw %}'
        name: ingest-metrics-generator
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/ingest-metrics-generator:146e872d3d4b6d75b4fb989509bada94b5148c3c
        resources: {}
