apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-data-generator
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: run-ingest-metrics-generator
      inputs:
        artifacts:
          - name: ingest_metrics_generator_settings
            path: /etc/ingest-metrics-generator-settings.yaml
        parameters:
          - name: num_messages
      container:
        command:
          - 'python'
          - 'main.py'
          - '--settings-file'
          - '/etc/ingest-metrics-generator-settings.yaml'
          - '--num-messages'
          - '{% raw %}{{inputs.parameters.num_messages}}{% endraw %}'
        name: ingest-metrics-generator
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/ingest-metrics-generator:2d0082f90640c75aa4808d84a7179b360589e6af
        resources: {}
