apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-data-generator
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: run-test
      container:
        command:
          - 'python'
          - '--settings-file'
          - '/tmp/ingest-metrics-generator-settings.yaml'
        name: ingest-metrics-generator
        #TODO update docker tag for image
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/ingest-metrics-generator:FIX_ME-1dc8ab4863bbfa0a98098bc229bf5e7637b8355f
        resources: {}
      inputs:
        artifacts:
          - name: ingest_metrics_generator_settings
            path: /tmp/ingest-metrics-generator-settings.yaml
      outputs: {}
