apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-deploy-locust
  namespace: argo
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:

  - name: locust-update-configuration
    inputs:
      parameters:
      - name: test_factory_sha
        value: '{% raw %}{{workflow.outputs.parameters.test_factory_sha}}{% endraw %}'
      # TODO: is there a way to dedupe this?
      artifacts:
        - name: test-factory-checkout
          path: /root/test-factory
          git:
            repo: 'git@github.com:getsentry/test-factory'
            revision: '{% raw %}{{inputs.parameters.test_factory_sha}}{% endraw %}'
            depth: 1
            sshPrivateKeySecret:
              name: ssh-deploy-key-test-factory
              key: ssh-private-key
    container:
      name: sentry-kube
      # getsentry/ops branch: feat/sentry-kube-no-context
      image: "europe-west3-docker.pkg.dev/sentry-st-testing/main/sentry-kube:f575c8bb772339b61bc0caa8a337dec24ddc2642"
      command:
      - bash
      - '-c'
      - |
        exec 2>&1
        set -euxo pipefail

        git status

        # Update ingest-load-tester version
        yq eval -i '.image_tag = "{% raw %}{{workflow.outputs.parameters.ingest_load_tester_sha}}{% endraw %}"' ./k8s/services/ingest-load-tester/_values.yaml

        # FIXME: sentry-kube should be updated to handle this
        # sentry-kube diff-beta ingest-load-tester
        sentry-kube render ingest-load-tester > _ingest-load-tester.yaml
        yq eval '(select(.kind == "Deployment") | .spec.template.metadata.annotations.argoWorkflowId) = "{% raw %}{{workflow.uid}}{% endraw %}"' _ingest-load-tester.yaml > _ingest-load-tester.processed.yaml
        # FIXME: do not hardcode namespaces
        sentry-kube kubectl apply -n default -f _ingest-load-tester.processed.yaml
    serviceAccountName: default

  - name: locust-wait-for-rollout
    container:
      name: kubectl
      image: bitnami/kubectl:1.19
      command:
      - bash
      - -c
      - |
        kubectl rollout status deployment --namespace=default ingest-load-tester-master --timeout=60s
        kubectl rollout status deployment --namespace=default ingest-load-tester-worker --timeout=60s
    serviceAccountName: default
