apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-influxdb-monitor
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: infulxdb-monitor
      container:
        command:
          - '/influxdb-monitor'
          - '--organisation'
          - 'sentry'
          - '--bucket-name'
          - 'statsd'
          - '--measurement'
          - 'kafka_consumer_lag'
        name: influxdb-monitor
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/influxdb-monitor:85194e6aaca30c0cbeee5e8f398d5d7e892f7422
        resources: {}
        env:
          - name: INFLUX_TOKEN
            valueFrom:
              secretKeyRef:
                name: influx-rw
                key: token
          - name: INFLUX_URL
            value: 'http://influxdb-server.default.svc.cluster.local'
