apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-influxdb-monitor
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: infulxdb-monitor
      container:
        command:
          - '/influxdb-monitor'
          - '--timeout'
          - '5m'
          - '--organisation'
          - '1'
          - '--bucket-name'
          - 'statsd'
          - '--measurement'
          - 'kafka_consumer_lag'
          - '--dry-run'
        name: influxdb-monitor
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/influxdb-monitor:d43d82ae9d408f0bd5e329aba4e354955de98233
        resources: {}
      env:
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influx-rw
              key: token
        - name: INFLUX_URL
          value: 'http://influxdb-server.default.svc.cluster.local'
