apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-influxdb-monitor
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: infulxdb-monitor
      container:
        command:
          - '/influxdb-monitor'
          - '--organisation'
          - 'sentry'
          - '--bucket-name'
          - 'statsd'
          - '--measurement'
          - 'kafka_consumer_lag'
        name: influxdb-monitor
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/influxdb-monitor:33d0298b352a9ff8e289224a268d00c388fea250
        resources: {}
        env:
          - name: INFLUX_TOKEN
            valueFrom:
              secretKeyRef:
                name: influx-rw
                key: token
          - name: INFLUX_URL
            value: 'http://{{ values.influxdb_hostname }}'
