apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-ingest-load-tester
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:

  - name: ingest-load-tester-update-configuration
    inputs:
      parameters:
      - name: test_factory_sha
        value: '{% raw %}{{workflow.outputs.parameters.test_factory_sha}}{% endraw %}'
      - name: wait_for_rollout
        value: '1'
      # TODO: is there a way to dedupe this?
      artifacts:
        - name: test-factory-checkout
          path: /root/test-factory
          git:
            repo: 'git@github.com:getsentry/test-factory'
            revision: '{% raw %}{{inputs.parameters.test_factory_sha}}{% endraw %}'
            depth: 1
            sshPrivateKeySecret:
              name: ssh-deploy-key-test-factory
              key: ssh-private-key
    container:
      name: sentry-kube
      image: {{ values.sentry_kube_image }}
      command:
      - bash
      - '-c'
      - |
        exec 2>&1
        set -euxo pipefail

        git status

        # Update ingest-load-tester version
        yq eval -i '.image_tag = "{% raw %}{{workflow.outputs.parameters.ingest_load_tester_sha}}{% endraw %}"' ./k8s/services/ingest-load-tester/_values.yaml
        yq eval -i '.image_tag = "{% raw %}{{workflow.outputs.parameters.ingest_load_tester_sha}}{% endraw %}"' ./k8s/services/fake-sentry/_values.yaml

        # FIXME: sentry-kube should be updated to handle this
        # sentry-kube diff-beta ingest-load-tester
        sentry-kube render ingest-load-tester > _ingest-load-tester.yaml
        sentry-kube render fake-sentry > _fake-sentry.yaml

        yq eval '(select(.kind == "Deployment") | .spec.template.metadata.annotations.argoWorkflowId) = "{% raw %}{{workflow.uid}}{% endraw %}"' _ingest-load-tester.yaml > _ingest-load-tester.processed.yaml
        yq eval '(select(.kind == "Deployment") | .spec.template.metadata.annotations.argoWorkflowId) = "{% raw %}{{workflow.uid}}{% endraw %}"' _fake-sentry.yaml > _fake-sentry.processed.yaml

        # FIXME: do not hardcode namespaces
        sentry-kube kubectl apply -n default -f _ingest-load-tester.processed.yaml
        sentry-kube kubectl apply -n default -f _fake-sentry.processed.yaml

        ### Wait for rollout, if told
        WAIT_FOR_ROLLOUT=$(echo "{% raw %}{{inputs.parameters.wait_for_rollout}}{% endraw %}" | tr '[:upper:]' '[:lower:]')
        TRUTHY_VALUES=("1" "yes" "true")

        if [[ " ${TRUTHY_VALUES[*]} " == *" ${WAIT_FOR_ROLLOUT} "* ]]; then
          echo "Waiting for the rollout to finish..."
          sentry-kube kubectl rollout status deployment --namespace=default ingest-load-tester-master --timeout=60s
          sentry-kube kubectl rollout status deployment --namespace=default ingest-load-tester-worker --timeout=60s
          sentry-kube kubectl rollout status deployment --namespace=default fake-sentry --timeout=60s
        fi
    serviceAccountName: default

  ttlStrategy:
    # 3 days
    secondsAfterCompletion: 259200
