apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-influxdb-monitor
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: infulxdb-monitor
      container:
        command:
          - '/influxdb-monitor'
          - '--timeout'
          - '5m'
          - '--organisation'
          - '1'
        name: influxdb-monitor
        image: europe-west3-docker.pkg.dev/sentry-st-testing/main/influxdb-monitor:2922af5b4f7e3d5dda74f54aed841c2cba3bfba1
        resources: {}
      env:
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influx-rw
              key: token
        - name: INFLUX_URL
          value: 'http://influxdb-server.default.svc.cluster.local'
