apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-kafka
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: flush-all-kafka
    container:
      name: flush-all-kafka
      image: confluentinc/cp-kafka:5.1.4
      command:
      - sh
      - -c
      - |
        exec 2>&1
        set -eux

        BOOTSTRAP_SERVER="ingest-kafka.default.svc.cluster.local:9092"
        ZK_SERVER="ingest-kafka.default.svc.cluster.local:2181"

        TOPICS_TO_DELETE=$(kafka-topics --zookeeper "${ZK_SERVER}" --list | grep -v '__' || true)

        for TOPIC in ${TOPICS_TO_DELETE}; do
          kafka-topics --zookeeper "${ZK_SERVER}" --delete --topic "${TOPIC}"
        done

        echo 'Done!'

  - name: apply-topic-config
    inputs:
      artifacts:
        - name: test-factory-src
          path: /opt/test-factory
    container:
      name: apply-topic-config
      image: europe-west3-docker.pkg.dev/sentry-st-testing/main/sentry-topicctl:d5508ec69aa38ff93b0b8e0931caacfc76a6733e
      command:
      - bash
      - -c
      - |
        exec 2>&1
        set -eux

        cd /opt/test-factory/config/kafka

        topicctl \
          --cluster-config cluster.yaml \
          apply \
          --skip-confirm \
          ./topics/*

        echo 'Done!'

  ttlStrategy:
    # 3 days
    secondsAfterCompletion: 259200
