apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-prepare-run
  namespace: argo
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: prepare-run
    inputs:
      artifacts:
      # We can clone it to a volume that'll be shared with the consequitive steps,
      # e.g. like here https://github.com/argoproj/argo-workflows/blob/master/examples/ci.yaml
      # The problem is that the volume will be ReadWriteOnce, so it won't be possible to use it
      # in different steps concurrently.
      - name: test-factory-checkout
        path: /root/test-factory
        git:
          repo: 'git@github.com:getsentry/test-factory'
          revision: '{% raw %}{{inputs.parameters.test_factory_branch}}{% endraw %}'
          # depth: 1
          sshPrivateKeySecret:
            name: ssh-deploy-key-test-factory
            key: ssh-private-key
      parameters:
      - name: test_factory_branch
        value: "main"
      - name: test_duration
        value: "30s"
      - name: test_users
        value: "10"
    container:
      image: "europe-west3-docker.pkg.dev/sentry-st-testing/main/sentry-kube:f575c8bb772339b61bc0caa8a337dec24ddc2642"
      command:
      - bash
      - '-c'
      - |
        # To avoid out of order stdout/stderr mess
        exec 2>&1
        set -euxo pipefail

        ROOT_DIR=$(pwd)
        MANIFEST_FILE="${ROOT_DIR}/run-manifest.yaml"
        cp "${MANIFEST_FILE}" /tmp/run-manifest.yaml

        DATA_GENERATOR_SETTINGS_FILE="${ROOT_DIR}/config/ingest-metrics-generator/settings.yaml"
        cp "${DATA_GENERATOR_SETTINGS_FILE}" /tmp/ingest-metrics-generator-settings.yaml

        RELAY_REV_ORIGINAL=$(yq e '.relay_revision' ${MANIFEST_FILE})
        INGEST_LOAD_TESTER_REV_ORIGINAL=$(yq e '.ingest_load_tester_revision' ${MANIFEST_FILE})

        ### Resolve test_factory revision
        git rev-parse HEAD | tee /tmp/test_factory_sha

        ### Resolve relay revision
        RELAY_REPO="https://github.com/getsentry/relay/"
        RELAY_DIR="/tmp/relay"
        git clone "${RELAY_REPO}" "${RELAY_DIR}"
        cd "${RELAY_DIR}"
        git checkout "${RELAY_REV_ORIGINAL}"
        git rev-parse HEAD | tee /tmp/relay_sha

        ### Resolve ingest-load-tester revision
        INGEST_LOAD_TESTER_REPO="https://github.com/getsentry/ingest-load-tester/"
        INGEST_LOAD_TESTER_DIR="/tmp/ingest-load-tester"
        git clone "${INGEST_LOAD_TESTER_REPO}" "${INGEST_LOAD_TESTER_DIR}"
        cd "${INGEST_LOAD_TESTER_DIR}"
        git checkout "${INGEST_LOAD_TESTER_REV_ORIGINAL}"
        git rev-parse HEAD | tee /tmp/ingest_load_tester_sha

        ### "Resolve" (FIXME) sentry revision
        SENTRY_REVISION=$(yq e '.sentry_revision' ${MANIFEST_FILE})
        echo "${SENTRY_REVISION}" | tee /tmp/sentry_sha

        ### Record Locust settings
        DEFAULT_STUB="default"
        OVERRIDE_USED="0"
        DEFAULT_DURATION="1m"
        DEFAULT_USERS=5

        TEST_DURATION='{% raw %}{{inputs.parameters.test_duration}}{% endraw %}'
        if [[ "${TEST_DURATION}" == "${DEFAULT_STUB}" ]]; then
          TEST_DURATION="${DEFAULT_DURATION}"
        else
          OVERRIDE_USED="1"
        fi

        TEST_USERS='{% raw %}{{inputs.parameters.test_users}}{% endraw %}'
        if [[ "${TEST_USERS}" == "${DEFAULT_STUB}" ]]; then
          TEST_USERS="${DEFAULT_USERS}"
        else
          OVERRIDE_USED="1"
        fi

        echo "${TEST_DURATION}" | tee /tmp/test_duration
        echo "${TEST_USERS}" | tee /tmp/test_users
        echo "${OVERRIDE_USED}" | tee /tmp/test_override

        set +x
        ### Print out some valuable info
        echo '### Manifest file'
        cat "${MANIFEST_FILE}"
        echo '---'

        # To reduce the directory size when archiving
        rm -rf "${ROOT_DIR}/.git"
    outputs:
      artifacts:
        - name: run_manifest
          path: /tmp/run-manifest.yaml
          globalName: run_manifest
        - name: ingest-metrics-generator-settings
          path: /tmp/ingest-metrics-generator-settings.yaml
          globalName: ingest_metrics_generator_settings
        - name: test-factory-src
          path: /root/test-factory
          globalName: test-factory-src
      parameters:
        - name: test_factory_sha
          valueFrom:
            path: /tmp/test_factory_sha
          globalName: test_factory_sha
        - name: relay_sha
          valueFrom:
            path: /tmp/relay_sha
          globalName: relay_sha
        - name: ingest_load_tester_sha
          valueFrom:
            path: /tmp/ingest_load_tester_sha
          globalName: ingest_load_tester_sha
        - name: sentry_sha
          valueFrom:
            path: /tmp/sentry_sha
          globalName: sentry_sha
        - name: test_duration
          valueFrom:
            path: /tmp/test_duration
          globalName: test_duration
        - name: test_users
          valueFrom:
            path: /tmp/test_users
          globalName: test_users
        - name: test_override
          valueFrom:
            path: /tmp/test_override
          globalName: test_override
  ttlStrategy:
    # 3 days
    secondsAfterCompletion: 259200
