apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-relay
  namespace: argo
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: relay-update-configuration
    inputs:
      parameters:
      - name: test_factory_sha
        value: '{% raw %}{{workflow.outputs.parameters.test_factory_sha}}{% endraw %}'
      - name: wait_for_rollout
        value: '1'
      artifacts:
      - name: test-factory-src
        path: /root/test-factory
    container:
      name: sentry-kube
      image: {{ values.sentry_kube_image }}
      command:
      - bash
      - '-c'
      - |
        exec 2>&1
        set -euxo pipefail

        git init

        # Update relay version
        yq eval -i '.environments.main.image_tag = "{% raw %}{{workflow.outputs.parameters.relay_sha}}{% endraw %}"' ./k8s/services/relay/_values.yaml

        # FIXME: sentry-kube should be updated to handle this
        # sentry-kube diff-beta relay
        sentry-kube render relay > _relay.yaml

        # Add an annotation with run ID
        yq eval '(select(.kind == "Deployment") | .spec.template.metadata.annotations.argoWorkflowId) = "{% raw %}{{workflow.uid}}{% endraw %}"' _relay.yaml > _relay.processed.yaml

        # FIXME: do not hardcode namespaces
        sentry-kube kubectl apply -n default -f _relay.processed.yaml

        ### Wait for rollout, if told
        WAIT_FOR_ROLLOUT=$(echo "{% raw %}{{inputs.parameters.wait_for_rollout}}{% endraw %}" | tr '[:upper:]' '[:lower:]')
        TRUTHY_VALUES=("1" "yes" "true")

        if [[ " ${TRUTHY_VALUES[*]} " == *" ${WAIT_FOR_ROLLOUT} "* ]]; then
          echo "Waiting for the rollout to finish..."
          sentry-kube kubectl rollout status deployment -n default relay-main --timeout=60s
        fi

    serviceAccountName: default

  ttlStrategy:
    # 3 days
    secondsAfterCompletion: 259200
