apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-run-test
  namespace: argo
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: run-test
    container:
      command:
      - bash
      - '-c'
      - |
        exec 2>&1
        set -euo pipefail

        TEST_DURATION="{% raw %}{{inputs.parameters.test_duration}}{% endraw %}"
        TEST_USERS="{% raw %}{{inputs.parameters.test_users}}{% endraw %}"
        MANUAL_OVERRIDE="{% raw %}{{inputs.parameters.test_override}}{% endraw %}"

        RUN_REPORT_FILE="/tmp/run-report.yaml"

        ARGS=(
          '--influx'
          'https://influxdb.testa.getsentry.net'
          --organisation
          'f1c58f1d769114e6'
          --board
          '08830e9216d27000'
          --report
          "${RUN_REPORT_FILE}"
        )

        if [[ "${MANUAL_OVERRIDE}" == "1" ]]; then
          ARGS+=(
            --users
            "${TEST_USERS}"
            --duration
            "${TEST_DURATION}"
          )
        else
          ARGS+=(
            --config
            /etc/run-manifest.yaml
          )
        fi
        set -x
        /load-starter ${ARGS[@]}

        cat "${RUN_REPORT_FILE}"
      env:
      - name: SLACK_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: slack-oauth-token
            key: token
      - name: SLACK_CHANNEL_ID
        value: '#feed-qa'
      - name: WORKFLOW_URL
        value: 'https://run.testa.getsentry.net/archived-workflows/argo/{% raw %}{{workflow.uid}}{% endraw %}'
      - name: WORKFLOW_ID
        value: '{% raw %}{{workflow.uid}}{% endraw %}'
      - name: WORKFLOW_COMMENT
        value: '{% raw %}{{inputs.parameters.test_comment}}{% endraw %}'
      name: load-starter
      image: europe-west3-docker.pkg.dev/sentry-st-testing/main/load-starter:1dc8ab4863bbfa0a98098bc229bf5e7637b8355f
      resources: {}
    inputs:
      parameters:
      - name: test_duration
      - name: test_users
      - name: test_override
      - name: test_comment
        value: '{% raw %}{{workflow.parameters.comment}}{% endraw %}'
      artifacts:
      - name: run_manifest
        path: /etc/run-manifest.yaml
    outputs:
      artifacts:
      - name: run_report
        path: /tmp/run-report.yaml
        globalName: run_report
  - name: run-stats-collector
    inputs:
      artifacts:
        - name: run_report
          path: /tmp/run-report.yaml
    outputs:
      artifacts:
        - name: stats_report
          path: /tmp/stats-report.yaml
          globalName: stats_report
    container:
      name: load-starter
      image: europe-west3-docker.pkg.dev/sentry-st-testing/main/stats-collector:2d0e65479482598304fd1aaae4fc6135525725d8
      command:
        - python
        - stats_collector.py
        - '--format'
        - yaml
        - '--multistage'
        - /tmp/run-report.yaml
        - '--out'
        - /tmp/stats-report.yaml
      env:
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influx-rw
              key: token
        - name: INFLUX_URL
          value: 'http://influxdb-server.default.svc.cluster.local'
