apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-run-test
  namespace: argo
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  podGC:
    strategy: OnWorkflowCompletion
  templates:
  - name: run-test
    container:
      command:
      - /load-starter
      - '--influx'
      - 'https://influxdb.testa.getsentry.net'
      - --organisation
      - 'f1c58f1d769114e6'
      - --board
      - '08830e9216d27000'
      - --config
      - /etc/run-manifest.yaml
      # - --duration
      # - '{% raw %}{{inputs.parameters.test_duration}}{% endraw %}'
      # - --users
      # - '{% raw %}{{inputs.parameters.test_users}}{% endraw %}'
      env:
      - name: SLACK_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: slack-oauth-token
            key: token
      - name: SLACK_CHANNEL_ID
        value: '#feed-qa'
      - name: WORKFLOW_URL
        value: 'https://run.testa.getsentry.net/archived-workflows/argo/{% raw %}{{workflow.uid}}{% endraw %}'
      - name: WORKFLOW_ID
        value: '{% raw %}{{workflow.uid}}{% endraw %}'
      name: load-starter
      image: europe-west3-docker.pkg.dev/sentry-st-testing/main/load-starter:c35476e75df8fa0f34265f5df7b1e66bc2772836
      resources: {}
    inputs:
      parameters:
      - name: test_duration
        value: '{% raw %}{{workflow.parameters.test_duration}}{% endraw %}'
      - name: test_users
        value: '{% raw %}{{workflow.parameters.test_users}}{% endraw %}'
      artifacts:
      - name: run_manifest
        path: /etc/run-manifest.yaml
