{%  set labels = {
  "service": "sentry",
  "component":"ingest-metrics-consumer",
} %}

  {% set image = values.image_name + ":" + values.image_tag %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ingest-metrics-consumer"
  labels: {{ labels }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ labels }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels: {{ labels }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: "{{ image }}"
          name: sentry
          args: ["run", "ingest-metrics-consumer"]
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
          volumeMounts:
            - name: sentry-config
              mountPath: /etc/sentry/config.yml
              subPath: config.yml
              readOnly: true
            - name: sentry-config
              mountPath: /etc/sentry/sentry.conf.py
              subPath: sentry.conf.py
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sleep
                  - "5"
      volumes:
        - name: sentry-config
          configMap:
            name: sentry-config
