# topicctl config
meta:
  name: default
  environment: test
  region: default
spec:
  bootstrapAddrs:
    - ingest-kafka.default.svc.cluster.local:9092
  zkAddrs:
    - ingest-kafka.default.svc.cluster.local:2181
  zkLockPath: /topicctl/locks
