# This is a proxy to InfluxDB that adds authorization header, essentially disabling annoying mandatory auth
# for end users.
#
# Caveat: without a valid token (e.g. when bootstrapping), you will not get past the sign-in screen, even with a
# valid username/password. To create a new token, use `kubectl port-forward statefulset/influxdb 8086:8086` and then sign in
# with the default username/password.

{% set labels = {
  "service": "influxdb-proxy",
  "component": "proxy",
} %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-proxy
  namespace: default
  labels: {{ labels }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ labels }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: {{ labels }}
    spec:
      initContainers:
      - image: busybox:1.32
        name: write-nginx-config
        command:
        - sh
        - -c
        - |
          echo '
          # Nginx config

          server {
            listen 80;
            location / {
              proxy_pass http://influxdb-server.default.svc.cluster.local:80;

              # With the token passed, InfluxDB will not ask for username/password every time.
              proxy_set_header Authorization "Token {{ values.influx_token }}";
            }

            # Ignore the sign-in page since auth should be handled transparently
            location /signin {
              return 302 /;
            }
          }
          ' > /etc/nginx/conf.d/default.conf
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/
      containers:
      - image: nginx:1.20
        name: nginx
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi
      volumes:
      - name: nginx-config
        emptyDir: {}
