apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  labels:
    service: influxdb
spec:
  storageClassName: premium-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
