{% set labels = {
  "service": "postgres",
  "component": "server",
} %}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sentry
  labels: {{ labels }}
spec:
  selector:
    matchLabels: {{ labels }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{ labels }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: postgres:13
        name: postgres-sentry
        env:
        - name: POSTGRES_PASSWORD
          value: 'postgres'
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-disk
          mountPath: /var/lib/postgresql/data
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "10"
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 4000m
            memory: 500Mi
      volumes:
      - name: postgres-disk
        persistentVolumeClaim:
          claimName: postgres-sentry-claim
