---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-sentry-claim
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
