---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim
  namespace: argo
  labels:
    serivce: argo-workflows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: argo
  labels:
    serivce: argo-workflows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
