{% set labels = {
  "service": "ingest-load-tester",
  "component": "master",
} %}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ labels }}
  name: ingest-load-tester-master
spec:
  replicas: 1
  selector:
    matchLabels: {{ labels }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: {{ labels }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ingest-load-tester
        image: "{{ values.image }}"
        imagePullPolicy: Always
        args: ["run-master"]
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
