apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: sentry-system
  labels:
    service: telegraf
data:
  telegraf.conf: |
    {% filter indent %}{% include 'templates/telegraf.conf' %}{% endfilter %}
