{% set component = 'worker' %}
{% set labels = {
  "service": "telegraf",
  "component": component,
} %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-worker
  namespace: sentry-system
  labels: {{ labels }}
spec:
  replicas: 6
  selector:
    matchLabels: {{ labels }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: {{ labels }}
      annotations:
        configVersion: "{{ md5template("templates/telegraf.conf") }}"
    spec:
      serviceAccountName: telegraf
      containers:
      - name: telegraf
        image: "{{ values.image }}"
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        env:
        - name: INFLUX_URL
          value: "{{ values.influx_url }}"
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influx-rw
              key: token
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 10000m
            memory: 1000Mi
      volumes:
      - name: config
        configMap:
          name: telegraf-worker
