{% set component = 'cluster-agent' %}
{% set labels = {
  "service": "telegraf",
  "component": component,
} %}
# Cluster-agent Deployment. Only one instance of it should be running in the cluster.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-cluster-agent
  namespace: sentry-system
  labels: {{ labels }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ labels }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: {{ labels }}
      annotations:
        configVersion: "{{ md5template("templates/telegraf.conf") }}"
    spec:
      serviceAccountName: telegraf
      containers:
      - name: telegraf
        image: "{{ values.image }}"
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        env:
        - name: INFLUX_URL
          value: "{{ values.influx_url }}"
        # FIXME: move it to a secret
        - name: INFLUX_TOKEN
          value: "{{ values.influx_token }}"
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
      volumes:
      - name: config
        configMap:
          name: telegraf-cluster-agent
