---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-workers
  namespace: sentry-system
  labels:
    service: telegraf
    component: worker
spec:
  selector:
    service: telegraf
    component: worker
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-proxy
  namespace: sentry-system
  labels:
    service: telegraf
    component: proxy
spec:
  selector:
    service: telegraf
    component: proxy
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
