# Config file for fake sentry (taken from https://github.com/getsentry/ingest-load-tester/blob/master/default_config/fake_sentry.config.yml)

# host ip for the server
host: 0.0.0.0
# port for the running server
port: 8000
# security key
key: "612a4a88a9cbee7f4cf5e8a2c42adc19"
# logging configuration
log:
  version: 1
  formatters:
    default:
      format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  handlers:
    console_logging:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: default
  loggers:
    werkzeug:  # infrastructure logger
      # DEBUG INFO WARNING ERROR CRITICAL
      level: WARNING
      propagate: false
      handlers:
        - console_logging
    fake_sentry.fake_sentry: # flask app logger
      level: DEBUG
      propagate: false
      handlers:
        - console_logging
  root: # general logger
    level: ERROR
    handlers:
      - console_logging
